#### Logostic regression w klasyfikacji binarner występowania raka piersi 

In [30]:
#importowanie modułów
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#### 1). Data loading

In [33]:
#import danych
breast_cancer = datasets.load_breast_cancer() 
x, y = breast_cancer.data, breast_cancer.target
print(breast_cancer.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [10]:
n_samples, n_features = x.shape
print(f'n_samples = {n_samples}, n_features = {n_features}')
print(x)

n_samples = 569, n_features = 30
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [12]:
for name, value in zip(breast_cancer.feature_names, x[0]):
    print(name, ":", value)

mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189


In [16]:
#podział na zbiór testowy i treningowy
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
print(x_train.shape, x_test.shape)

(455, 30) (114, 30)


In [20]:
#skalowanie danych uczących
sc = StandardScaler()
sc.fit(x_train)
print('Średnie cech:')
print(sc.mean_)
print('Odchylenia standardowe cech:')
print(sc.scale_)

Średnie cech:
[1.42134923e+01 1.93543736e+01 9.25727912e+01 6.64583077e+02
 9.63717582e-02 1.05058879e-01 8.96509136e-02 4.95899780e-02
 1.81131209e-01 6.27204835e-02 4.12704615e-01 1.22476747e+00
 2.91436725e+00 4.17422967e+01 7.01670989e-03 2.58046242e-02
 3.18617881e-02 1.18816593e-02 2.05152879e-02 3.82098967e-03
 1.64117868e+01 2.57051648e+01 1.08253319e+02 9.00190549e+02
 1.32138198e-01 2.56131407e-01 2.72104193e-01 1.15820371e-01
 2.88476484e-01 8.36364615e-02]
Odchylenia standardowe cech:
[3.61393415e+00 4.39478887e+00 2.49663565e+01 3.62204367e+02
 1.37309337e-02 5.19197492e-02 8.01752926e-02 3.93686243e-02
 2.72271211e-02 6.71035406e-03 2.87068914e-01 5.74298327e-01
 2.09734645e+00 4.85007708e+01 3.05760659e-03 1.80992367e-02
 2.91334637e-02 6.28200536e-03 8.26851979e-03 2.76617334e-03
 5.00827710e+00 6.28235900e+00 3.48114950e+01 5.94523660e+02
 2.21654518e-02 1.54650615e-01 2.04049117e-01 6.69564801e-02
 5.87803649e-02 1.66278736e-02]


In [22]:
x_train = sc.transform(x_train)
#x_train = sc.fit_transform(x_train)
print(x_train.mean(), x_train.std())

1.2284841438782686e-16 1.0


In [24]:
#transformacja danych testowych
x_test = sc.transform(x_test)

In [26]:
#konwersja numpy->torch
x_train = torch.from_numpy(x_train.astype(np.float32))
x_test = torch.from_numpy(x_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))
y_train.shape

torch.Size([455])

In [28]:
#przekształcenie do wektorów kolumnowych
y_train = y_train.view(y_train.shape[0],1)
y_test = y_test.view(y_test.shape[0],1)
y_train.shape

torch.Size([455, 1])

#### 2). Model

zdefiniuj klasę dziedziczącą po nn.Module, model liniowy + funkcja aktywacji sigmoid, 1 warstwa

In [23]:
#your code here

#### 3). Loss + optimizer

In [42]:
#your code here (SGD + binary cross entropy)

#### 4). Trainning loop

In [45]:
#your code here

In [49]:
#data evaluation
with torch.no_grad():
    y_pred = model(x_test)
    print(y_pred)
    y_pred_round = y_pred.round()
    print(y_pred_round)
    acc = y_pred_round.eq(y_test).sum() / float(y_test.shape[0])
    print(f'accuracy = {acc:.4f}')

NameError: name 'model' is not defined